steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - "--no-cache"
      - "-t"
      - "$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA"
      - --build-arg
      - VITE_FIREBASE_API_KEY=$_FIREBASE_API_KEY
      - --build-arg
      - VITE_FIREBASE_AUTH_DOMAIN=$_FIREBASE_AUTH_DOMAIN
      - --build-arg
      - VITE_FIREBASE_DB_URL=$_FIREBASE_DB_URL
      - --build-arg
      - VITE_FIREBASE_PROJ_ID=$_FIREBASE_PROJ_ID
      - --build-arg
      - VITE_FIREBASE_STORAGE_BUCKET=$_FIREBASE_STORAGE_BUCKET
      - --build-arg
      - VITE_FIREBASE_MSG_SENDER_ID=$_FIREBASE_MSG_SENDER_ID
      - --build-arg
      - VITE_FIREBASE_APP_ID=$_FIREBASE_APP_ID
      - --build-arg
      - VITE_FIREBASE_MEASUREMENT_ID=$_FIREBASE_MEASUREMENT_ID
      - --build-arg
      - VITE_APP_BASE_URL=$_APP_BASE_URL
      - --build-arg
      - VITE_APP_API_URL=$_APP_API_URL
      - .
      - "-f"
      - Dockerfile
    id: Build
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - "$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA"
    id: Push
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - "--platform=managed"
      - "--image=$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA"
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID,$_LABELS
      - "--region=$_DEPLOY_REGION"
      - "--quiet"
    id: Deploy
    entrypoint: gcloud
images:
  - "$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA"
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _DEPLOY_REGION: asia-east1
  _LABELS: gcb-trigger-id=2e56b391-e770-43ce-95ea-35a55330211c
  _TRIGGER_ID: 2e56b391-e770-43ce-95ea-35a55330211c
  _GCR_HOSTNAME: asia.gcr.io
  _PLATFORM: managed
  _SERVICE_NAME: sync-frontend
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - sync-frontend
